name: Repository
on:
  issues:
    types:
      - opened
      - edited
      - deleted
env: 
  dismiss_pull_request_Team: Synergy-Admins
  check_build_status: build,test
  Admin: Chandrasekhar674
  Writer: SynergyDevops
  TOKEN: ${{ secrets.TEST }}
  reponame: GITHUB_ENV
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Getting a reponame from issue
      if: contains(github.event.issue.labels.*.name, 'policies')
      run: | 
         echo "Testing Issue body"
         echo "${{ github.event.issue.number }}"
         echo "reponame=$(curl \
         -H "Authorization: token ${{ env.TEST }}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/Adminasaselfservice/issues/"${{ github.event.issue.number }}" | grep body | grep -oP '(?<=reponame:)\D+\w+' )" >> $GITHUB_ENV
    

