# This is a basic workflow to help you get started with Actions

name: Test Repository 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types:
      -opened
      -edited
      -closed
env:
  check_build_status: build,test
  Admin: Chandrasekhar674
  Writer: Chandrasekhar674
  TOKEN: ${{ Test.TOKEN }}
  reponame: Adminasaselfservice

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Getting a reponame from issue
      if: contains(github.event.issue.labels.*.name, 'policies')
      run: | 
         echo "Testing Issue body"
         echo "${{ github.event.issue.number }}"
         echo "reponame=$(curl \
         -H "Authorization: token ${{ Test.TOKEN }}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/mddeepu8/Adminasaselfservice/issues/"${{ github.event.issue.number }}" | grep body | grep -oP '(?<=reponame:)\D+\w+' )" >> $Adminasaselfservice
    
          
